name: "SvelteKit Static Deploy"
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Install and Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION || 'lts' }}
          check-latest: true
  
      - name: Install Dependencies
        run: |
          npm ci
  
      - name: Build the project
          npm run build
          
  deploy-ssh:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ vars.MODE == 'ssh' }}
    environment: ${{ inputs.environment }}
    steps:
    
      - name: Install rsync
        run: |
          sudo apt-get install rsync
  
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
            key: ${{ secrets.SERVER_SSH_KEY }}
            name: 'id_rsa'
            known_hosts: ${{ vars.SERVER_FINGERPRINT }}
            if_key_exists: 'replace'
  
      - name: Sync Build to Deployment via SSH
        env:
          SSH_USER: ${{ vars.SERVER_USER }}
          SERVER: ${{ vars.SERVER_HOST }}
          REMOTE_PATH: ${{ vars.SERVER_PATH }}
        run: |
          rsync -rltvch --delete --compress --chmod=755 -e "ssh -vv" \
          "./build/deploy/" "${SSH_USER}@${SERVER}:${REMOTE_PATH}"

  deploy-ftp:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ vars.MODE == 'ftp' }}
    environment: ${{ inputs.environment }}
    steps:

      - name: Sync Build to Deployment via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          password: ${{ secrets.SERVER_FTP_PASSWORD }}
          local-dir: './build/deploy/'
          server-dir: '${{ vars.SERVER_PATH }}/'
          dry-run: true
